### ISSUE TITLE
Integration with FoBiS

### ISSUE THREAD

**Issue by Tobychev** [szaghi/PreForM#1]
Hello Stefano! I'm back to writing fortran again! 
I wonder if there is a way to specify where the resulting files from PreForm end up if one uses it together with FoBiS. From looking at the documentation I can't tell if there is.

**Comment by szaghi** [comment]
Hi Tomas,

Fortran rocks, welcome back!

If you specify to use PreForM within FoBiS (`preform = True`) the postprocessed files are placed into the same directory of the original non processed file. Note that the original are not overwritten because a suffix is added (`.pfm`) before the file extension. Presently, I have not introduced a flag for customize the location of processed file. Do you want such a feature?

See you

**Comment by Tobychev** [comment]
Yes, since the processed files are in this case a result of the build, I would like to be able to tell FoBiS to put them in the build directory. 

On the other hand maybe I will late find it more sensible to have the processes and unprocessed files next to each other to make diffing simpler. On the third hand having the source next to the processed files might make it too easy to change the processed file instead of the source by mistake.

I guess I at least want the option to specify it, and then you can leave the default however you save the most work ;)

**Comment by szaghi** [comment]
Wow... you have 3 hands!

Ok, I am now trying to implement this feature.

I cannot safely merge your previous pull request. Just wait some minutes and I hope your fork and mine can be merged.

See you.

**Comment by szaghi** [comment]
Tomas,

I have just pushed the new FoBiS with the requested feature. Anyhow, I was wrong: if not specified the sources preprocessed with PreForM are removed after they are used. Now, if you specify a directory they are saved...

**Comment by szaghi** [comment]
The new feature is not documented... to use it just use the CLI switches 

``` bash
FoBiS.py --pfm_dir 'your_dir/' --preform
```

or the short version

``` bash
FoBiS.py --dpfm 'your_dir/' --preform
```

As the other switches you can put it inside fobos (long version):

``` ini
pfm_dir = your_dir/
```

Note that as `mod_dir` and `obj_dir`, `pfm_dir` is relative to `build_dir`. If it is not defined the previous behavior is valid: the preprocessor outputs are removed after used.

**Comment by Tobychev** [comment]
Thanks, this will be useful for debugging and make a more portable version of  the sources for distributed to those poor people without PreForM :)
