### ISSUE TITLE
pip install PreForM.py does not create PreForM.py but PreForM

### ISSUE THREAD

**Issue by zhouguidi** [szaghi/PreForM#4]
Hi,

On my machine (Ubuntu 16.04.2, python 2.7.12, pip 8.1.1), after running pip install PreForM.py, in $HOME/.local/bin there's no PreForM.py file created, instead a PreForM file. So running FoBiS.py build -pfm would report an error complaining about PreForM.py not found. Of course one can ln -s PreForM PreForM.py, but this should be working out of the box.

Please fix this. Thanks.

Guidi

**Comment by szaghi** [comment]
@zhouguidi 

This should be fixed in the new 1.1.3 version uploaded to PyPi

``` shell
stefano@zaghi(04:37 PM Fri Sep 02)
~/test 1 files, 20Kb
→ source venv/bin/activate
(venv)
stefano@zaghi(04:37 PM Fri Sep 02) pvenv {venv}
~/test 1 files, 20Kb
→ pip install -I PreForM.py==1.1.3
Collecting PreForM.py==1.1.3
Collecting argparse (from PreForM.py==1.1.3)
  Using cached argparse-1.4.0-py2.py3-none-any.whl
Installing collected packages: argparse, PreForM.py
Successfully installed PreForM.py-1.1.3 argparse-1.4.0
(venv)
stefano@zaghi(04:37 PM Fri Sep 02) pvenv {venv}
~/test 1 files, 20Kb
→ which PreForM.py
/home/stefano/test/venv/bin/PreForM.py
```

Note that I have specified the last version explicitly because (I do not why) pip was still trying to install the previous 1.1.2...

Let me know if this works also for you.

Thank you for reporting this bug.

Cheers.
